import type { Metadata } from "next";
import { Poppins, Volkhov } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { Providers } from "@/providers/providers";
import NavBar from "@/components/common/NavBar";
import FooterSection from "@/components/sections/FooterSection";

export const metadata: Metadata = {
  title: "Terms & Conditions",
  description: "",
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <main className="relative poppins  md:px-[9rem]">
        <NavBar />
        <div className="px-4 flex flex-col gap-[7.69rem]">
          {children}
          <FooterSection />
        </div>
      </main>
    </>
  );
}

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
